/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "impl/pch.h"

#include "snappydata_constants.h"

namespace io { namespace snappydata { namespace thrift {

const snappydataConstants g_snappydata_constants;

snappydataConstants::snappydataConstants() {
}

}}} // namespace

